name: Create Release

on:
  push:
    branches:      
      - main


jobs:
  create-release:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        uses: actions/create-release@v1

        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: v1.0
          release_name: 'Its a testing release'
          draft: false
          prerelease: false
